# ~/.config/hypr/hyprlock.conf

general {
    disable_loading_bar = true
    grace = 0
    hide_cursor = false
}

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 8

    noise = 0.01
    contrast = 1.0
    brightness = 0.9
    vibrancy = 0.2
}

animations {
    bezier = linear, 1, 1, 0, 0
    animation = fadeOut, 1, 1.8, linear
}

input-field {
    monitor =
    size = 400, 55
    outline_thickness = 3

    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true

    shadow_passes = 3
    shadow_size = 5

    outer_color = rgba(89b4faaa)
    inner_color = rgba(00000080)
    font_color = rgba(cdd6f4ff)

    fade_on_empty = false
    placeholder_text = <i>ENTER THE PASSWORD</i>

    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 100
    color = rgba(cdd6f4ff)
    

    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = <i>Hello, <b>$USER</b>!</i>
    font_size = 20
    color = rgba(cdd6f4ff)
    

    position = 0, 70
    halign = center
    valign = center

}


