

#colors
source = ~/.cache/wal/colors-hyprland.conf

#configs
source = ./hyprconfigs/binds.conf
source = ./hyprconfigs/plugins.conf
source = ./hyprconfigs/animations.conf



################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor =,1920x1080@60,0x0,1


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/


$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun


#################
### AUTOSTART ###
#################

exec-once = dms run
exec-once = hyprpaper &
exec-once = swaync &
exec-once = hyprpm reload &

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"  # for GTK4 apps
windowrulev2 = noborder,class:^(org.gnome.Nautilus)$

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/



env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Twilight

env = HYPRCURSOR_THEME,Twilight
env = HYPRCURSOR_SIZE,24




###################
### PERMISSIONS ###
###################



#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 15
    gaps_out = 3

    border_size = 1

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $foreground 
    col.inactive_border = $background

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true
    

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = scrolling
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 15
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.98
    inactive_opacity = 0.89

    shadow {
        enabled = true
        range = 5
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 2

        vibrancy = 0.1696
    }
}


# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0# Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
gesture = 3, down, close

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}




##############################
### WINDOWS AND WORKSPACES ###
##############################


windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# Sets the bar color in red for all windows that have 'myClass' as a class


source = ./dms/cursor.conf
